FROM ubuntu:14.04
MAINTAINER Stefan Janssen, stefan.m.janssen@gmail.com
ENV TOOLNAME metacv

#needed if on Michaels cluster
#~ ENV http_proxy http://172.16.20.249:3128
#~ ENV https_proxy http://172.16.20.249:3128

#update underlying linux system
RUN apt-get update -y

#list of all dependencies that can be satisfied via the package management system of Ubuntu
ENV PACKAGES wget g++ gcc make seqtk patch git ca-certificates xz-utils
#install dependencies
RUN apt-get install -y --no-install-recommends ${PACKAGES}

#directory where additional software shall be installed
ENV PREFIX /biobox/
#create prefix directory and src subdirectory
RUN mkdir -p ${PREFIX}/src/ ${PREFIX}/bin/ ${PREFIX}/lib/ ${PREFIX}/share/ 
ENV PATH=${PREFIX}/bin:${PATH}

# Locations for biobox file validator
ENV VALIDATOR /bbx/validator/
ENV BASE_URL https://s3-us-west-1.amazonaws.com/bioboxes-tools/validate-biobox-file
ENV VERSION  0.x.y
RUN mkdir -p ${VALIDATOR}
# download the validate-biobox-file binary and extract it to the directory $VALIDATOR
RUN wget \
      --quiet \
      --output-document -\
      ${BASE_URL}/${VERSION}/validate-biobox-file.tar.xz \
    | tar xJf - \
      --directory ${VALIDATOR} \
      --strip-components=1
ENV PATH ${PATH}:${VALIDATOR}
#download yaml schema
RUN wget -q -O ${PREFIX}/share/schema.yaml https://raw.githubusercontent.com/pbelmann/rfc/feature/new-profiling-inteface/container/profiling/schema.yaml



RUN wget -q -O ${PREFIX}/src/${TOOLNAME}.tgz http://downloads.sourceforge.net/project/metacv/metacv_2_3_0.tgz
RUN tar xzvf ${PREFIX}/src/${TOOLNAME}.tgz -C ${PREFIX}/src/
RUN mv ${PREFIX}/src/metacv_* ${PREFIX}/src/${TOOLNAME}/
RUN rm -f ${PREFIX}/src/${TOOLNAME}.tgz
RUN cd ${PREFIX}/src/${TOOLNAME}/ && make
RUN mv ${PREFIX}/src/${TOOLNAME}/metacv ${PREFIX}/bin/

RUN mkdir -p ${PREFIX}/share/metacv_database/
RUN wget -q -O ${PREFIX}/share/metacv_database/db.part00 http://downloads.sourceforge.net/project/metacv/cvdb_2059/db.part00
RUN wget -q -O ${PREFIX}/share/metacv_database/db.part01 http://downloads.sourceforge.net/project/metacv/cvdb_2059/db.part01
RUN wget -q -O ${PREFIX}/share/metacv_database/db.part02 http://downloads.sourceforge.net/project/metacv/cvdb_2059/db.part02
RUN wget -q -O ${PREFIX}/share/metacv_database/db.part03 http://downloads.sourceforge.net/project/metacv/cvdb_2059/db.part03
RUN wget -q -O ${PREFIX}/share/metacv_database/db.part04 http://downloads.sourceforge.net/project/metacv/cvdb_2059/db.part04
RUN wget -q -O ${PREFIX}/share/metacv_database/db.part05 http://downloads.sourceforge.net/project/metacv/cvdb_2059/db.part05
RUN wget -q -O ${PREFIX}/share/metacv_database/db.part06 http://downloads.sourceforge.net/project/metacv/cvdb_2059/db.part06
RUN wget -q -O ${PREFIX}/share/metacv_database/db.part07 http://downloads.sourceforge.net/project/metacv/cvdb_2059/db.part07
RUN cd ${PREFIX}/share/metacv_database/ && cat db.part* | tar xvfzp -
RUN rm -f ${PREFIX}/share/metacv_database/db.part*


#download the NCBI taxonomy from NCBI's FTP server
ADD downloadTaxonomy.pl ${PREFIX}/bin/
RUN downloadTaxonomy.pl ${PREFIX}/share/taxonomy/

#add my Perl scripts
ADD Utils.pm ${PREFIX}/lib/
ADD YAML.pm ${PREFIX}/lib/
ADD ${TOOLNAME}/convert_${TOOLNAME}.pl ${PREFIX}/bin/convert.pl
ADD ${TOOLNAME}/task_${TOOLNAME}.pl ${PREFIX}/bin/task.pl
ADD ${TOOLNAME}/deinterleave.pl ${PREFIX}/bin/deinterleave.pl
RUN chmod a+x ${PREFIX}/bin/task.pl ${PREFIX}/bin/downloadTaxonomy.pl ${PREFIX}/bin/convert.pl ${PREFIX}/bin/deinterleave.pl

ENV YAML "/bbx/mnt/input/biobox.yaml"
ENTRYPOINT ["task.pl"]
