FROM ubuntu:14.04
MAINTAINER Stefan Janssen, stefan.m.janssen@gmail.com
ENV TOOLNAME metacv

#needed if on Michaels cluster
#~ ENV http_proxy http://172.16.20.249:3128
#~ ENV https_proxy http://172.16.20.249:3128

#update underlying linux system
RUN apt-get update -y

#list of all dependencies that can be satisfied via the package management system of Ubuntu
ENV PACKAGES wget g++ gcc make seqtk patch git ca-certificates xz-utils
#install dependencies
RUN apt-get install -y --no-install-recommends ${PACKAGES}

#directory where additional software shall be installed
ENV PREFIX /biobox/
#create prefix directory and src subdirectory
RUN mkdir -p ${PREFIX}/src/ ${PREFIX}/bin/ ${PREFIX}/lib/ ${PREFIX}/share/ 
ENV PATH=${PREFIX}/bin:${PATH}

# Locations for biobox file validator
ENV VALIDATOR /bbx/validator/
ENV BASE_URL https://s3-us-west-1.amazonaws.com/bioboxes-tools/validate-biobox-file
ENV VERSION  0.x.y
RUN mkdir -p ${VALIDATOR}
# download the validate-biobox-file binary and extract it to the directory $VALIDATOR
RUN wget \
      --quiet \
      --output-document -\
      ${BASE_URL}/${VERSION}/validate-biobox-file.tar.xz \
    | tar xJf - \
      --directory ${VALIDATOR} \
      --strip-components=1
ENV PATH ${PATH}:${VALIDATOR}
#download yaml schema
RUN wget -q -O ${PREFIX}/share/schema.yaml https://raw.githubusercontent.com/pbelmann/rfc/feature/new-profiling-inteface/container/profiling/schema.yaml



RUN wget -q -O ${PREFIX}/src/${TOOLNAME}.tgz http://downloads.sourceforge.net/project/metacv/metacv_2_3_0.tgz
RUN tar xzvf ${PREFIX}/src/${TOOLNAME}.tgz -C ${PREFIX}/src/
RUN mv ${PREFIX}/src/metacv_* ${PREFIX}/src/${TOOLNAME}/
RUN rm -f ${PREFIX}/src/${TOOLNAME}.tgz
RUN cd ${PREFIX}/src/${TOOLNAME}/ && make
RUN mv ${PREFIX}/src/${TOOLNAME}/metacv ${PREFIX}/bin/

#from now on, the database should be provided by the host as a volume mount!
#~ ENV DBURL http://www.techfak.uni-bielefeld.de/ags/pi/pages/metacv
#~ RUN mkdir -p ${PREFIX}/share/metacv_database/
#~ RUN wget -q -O ${PREFIX}/share/metacv_database/db.part00 ${DBURL}/db.part00
#~ RUN wget -q -O ${PREFIX}/share/metacv_database/db.part01 ${DBURL}/db.part01
#~ RUN wget -q -O ${PREFIX}/share/metacv_database/db.part02 ${DBURL}/db.part02
#~ RUN wget -q -O ${PREFIX}/share/metacv_database/db.part03 ${DBURL}/db.part03
#~ RUN wget -q -O ${PREFIX}/share/metacv_database/db.part04 ${DBURL}/db.part04
#~ RUN wget -q -O ${PREFIX}/share/metacv_database/db.part05 ${DBURL}/db.part05
#~ RUN wget -q -O ${PREFIX}/share/metacv_database/db.part06 ${DBURL}/db.part06
#~ RUN wget -q -O ${PREFIX}/share/metacv_database/db.part07 ${DBURL}/db.part07
#~ RUN cd ${PREFIX}/share/metacv_database/ && cat db.part* | tar xvfzp -
#~ RUN rm -f ${PREFIX}/share/metacv_database/db.part*
#~ RUN echo "please make sure, that you have downloaded and extracted metaCV's database. Current URL is ${DBURL}. Extract like 'cat db.part* | tar xvfzp -p"

ENV GITHUB https://raw.githubusercontent.com/CAMI-challenge/docker_profiling_tools/master/
#download the NCBI taxonomy from NCBI's FTP server
RUN wget -q -O ${PREFIX}/bin/downloadTaxonomy.pl ${GITHUB}/downloadTaxonomy.pl
RUN chmod a+x ${PREFIX}/bin/downloadTaxonomy.pl
RUN downloadTaxonomy.pl ${PREFIX}/share/taxonomy/

#add my Perl scripts
RUN wget -q -O ${PREFIX}/lib/Utils.pm ${GITHUB}/Utils.pm
RUN wget -q -O ${PREFIX}/lib/YAML.pm ${GITHUB}/YAML.pm
ADD convert_${TOOLNAME}.pl ${PREFIX}/bin/convert.pl
ADD task_${TOOLNAME}.pl ${PREFIX}/bin/task.pl
ADD deinterleave.pl ${PREFIX}/bin/deinterleave.pl
RUN chmod a+x ${PREFIX}/bin/task.pl ${PREFIX}/bin/convert.pl ${PREFIX}/bin/deinterleave.pl

ENV YAML "/bbx/mnt/input/biobox.yaml"
ENTRYPOINT ["task.pl"]
