FROM ubuntu:14.04
MAINTAINER Stefan Janssen, stefan.m.janssen@gmail.com
ENV TOOLNAME tipp

#needed if on Michaels cluster
#~ ENV http_proxy http://172.16.20.249:3128
#~ ENV https_proxy http://172.16.20.249:3128

#update underlying linux system
RUN apt-get update -y

#list of all dependencies that can be satisfied via the package management system of Ubuntu
ENV PACKAGES wget curl bc unzip python default-jre ncbi-blast+ git seqtk make
#install dependencies
RUN apt-get install -y --no-install-recommends ${PACKAGES}

#directory where additional software shall be installed
ENV PREFIX /biobox/
#create prefix directory and src subdirectory
RUN mkdir -p ${PREFIX}/src/ ${PREFIX}/bin/ ${PREFIX}/lib/ ${PREFIX}/share/ 
ENV PATH=${PREFIX}/bin:${PATH}



#downloading marker
RUN wget -q -O ${PREFIX}/share/tipp.zip www.cs.utexas.edu/~phylo/software/sepp/tipp.zip
RUN unzip -d ${PREFIX}/share/ ${PREFIX}/share/tipp.zip
RUN rm -f ${PREFIX}/share/tipp.zip
RUN tar xzvf ${PREFIX}/share/${TOOLNAME}/refpkg.tar.gz -C ${PREFIX}/share/${TOOLNAME}/
ENV REFERENCE ${PREFIX}/share/tipp/
ENV BLAST /usr/bin/blastn

#install SEPP
RUN git config --global url."https://".insteadOf git://
RUN git clone https://github.com/smirarab/sepp ${PREFIX}/src/sepp
RUN cd ${PREFIX}/src/sepp && python setup.py install && python setup.py config
ENV PATH=${HOME}/.sepp/bundled-v3.0/:${PATH}

#download TIPP
RUN wget -q -O ${PREFIX}/src/${TOOLNAME}.zip http://www.cs.utexas.edu/~phylo/software/sepp/tipp-submission/master.zip
#extract downloaded archive
RUN unzip -d ${PREFIX}/src/ ${PREFIX}/src/${TOOLNAME}.zip
RUN mv ${PREFIX}/src/sepp-master* ${PREFIX}/src/${TOOLNAME}
RUN rm -f ${PREFIX}/src/${TOOLNAME}.zip
RUN sed -i "s/version = \"2.2.1\"/version = \"3.0\"/" ${PREFIX}/src/${TOOLNAME}/setup.py
RUN cd ${PREFIX}/src/${TOOLNAME} && python setup.py tipp

#change TIPP such that it print taxonids instead of taxon names
RUN sed -i "s/tax_name/tax_id/" /usr/local/lib/python2.7/dist-packages/sepp-3.0-py2.7.egg/sepp/metagenomics.py



#download the NCBI taxonomy from NCBI's FTP server
ADD downloadTaxonomy.pl ${PREFIX}/bin/
RUN downloadTaxonomy.pl ${PREFIX}/share/taxonomy/

#add my Perl scripts
ADD Utils.pm ${PREFIX}/lib/
ADD YAML.pm ${PREFIX}/lib/
ADD ${TOOLNAME}/convert_${TOOLNAME}.pl ${PREFIX}/bin/convert.pl
ADD ${TOOLNAME}/task_${TOOLNAME}.pl ${PREFIX}/bin/task.pl
RUN chmod a+x ${PREFIX}/bin/task.pl ${PREFIX}/bin/downloadTaxonomy.pl ${PREFIX}/bin/convert.pl 

ENV YAML "/bbx/input/biobox.yaml"
ENTRYPOINT ["task.pl"]
