FROM ubuntu:14.04
MAINTAINER Stefan Janssen, stefan.m.janssen@gmail.com
ENV TOOLNAME metaphyler

#needed if on Michaels cluster
#~ ENV http_proxy http://172.16.20.249:3128
#~ ENV https_proxy http://172.16.20.249:3128

#update underlying linux system
RUN apt-get update -y

#list of all dependencies that can be satisfied via the package management system of Ubuntu
ENV PACKAGES wget curl bc ncbi-blast+ ca-certificates make libc6-dev libc-dev gcc-4.8-locales gcc-multilib manpages-dev autoconf automake1.9 libtool flex bison gdb gcc-4.8-multilib libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan0-dbg libtsan0-dbg libquadmath0-dbg gcc g++ seqtk patch
#install dependencies
RUN apt-get install -y --no-install-recommends ${PACKAGES}

#directory where additional software shall be installed
ENV PREFIX /biobox/
#create prefix directory and src subdirectory
RUN mkdir -p ${PREFIX}/src/ ${PREFIX}/bin/ ${PREFIX}/lib/ ${PREFIX}/share/ 
ENV PATH=${PREFIX}/bin:${PATH}



#download the latest version of MetaPhyler
RUN wget -q -O ${PREFIX}/src/${TOOLNAME}.tar.gz http://metaphyler.cbcb.umd.edu/MetaPhylerV1.25.tar.gz
RUN tar xzvf ${PREFIX}/src/${TOOLNAME}.tar.gz -C ${PREFIX}/src/
RUN rm -f ${PREFIX}/src/${TOOLNAME}.tar.gz
RUN mv ${PREFIX}/src/MetaPhylerV1.25/ ${PREFIX}/src/${TOOLNAME}/
#patch metaphyler to use NCBI blast
ADD ${TOOLNAME}/runMetaphyler.pl.patch ${PREFIX}/src/${TOOLNAME}/
RUN patch ${PREFIX}/src/${TOOLNAME}/runMetaphyler.pl < ${PREFIX}/src/${TOOLNAME}/runMetaphyler.pl.patch



#add my Perl scripts
ADD Utils.pm ${PREFIX}/lib/
ADD ${TOOLNAME}/convert_${TOOLNAME}.pl ${PREFIX}/bin/convert.pl
ADD downloadTaxonomy.pl ${PREFIX}/bin/
ADD ${TOOLNAME}/task_${TOOLNAME}.pl ${PREFIX}/bin/task.pl
RUN chmod a+x ${PREFIX}/bin/task.pl ${PREFIX}/bin/downloadTaxonomy.pl ${PREFIX}/bin/convert.pl 

#download Perl YAML parser directly from CPAN site, since cpan does not easily work with proxies
RUN mkdir -p ${PREFIX}/lib/YAML/
RUN wget -q -O ${PREFIX}/lib/YAML/Tiny.pm http://cpansearch.perl.org/src/ETHER/YAML-Tiny-1.69/lib/YAML/Tiny.pm

#download the NCBI taxonomy from NCBI's FTP server
RUN downloadTaxonomy.pl ${PREFIX}/share/taxonomy/

ENV YAML "/bbx/input/biobox.yaml"
ENTRYPOINT ["task.pl"]
