FROM linsalrob/cfk8bd:latest
MAINTAINER Stefan Janssen, stefan.m.janssen@gmail.com
ENV TOOLNAME focus

#needed if on Michaels cluster
ENV http_proxy http://172.16.20.249:3128
ENV https_proxy http://172.16.20.249:3128

#update underlying linux system
RUN apt-get update -y

#list of all dependencies that can be satisfied via the package management system of Ubuntu
ENV PACKAGES wget curl unzip seqtk
#install dependencies
RUN apt-get install -y --no-install-recommends ${PACKAGES}


#directory where additional software shall be installed
ENV PREFIX /biobox/
#directory for in and output with the host system
ENV IO /exchange/


#create prefix directory and src subdirectory
RUN mkdir -p ${PREFIX}/bin/
RUN mkdir -p ${PREFIX}/src/${TOOLNAME}/
RUN mkdir -p ${PREFIX}/share/

RUN mkdir -p ${IO}/input/
RUN mkdir -p ${IO}/output/

RUN mv /home/* ${PREFIX}/src/${TOOLNAME}/

ENV MAPPERNAME IDmapper
ADD Utils.pm ${PREFIX}/src/${MAPPERNAME}/

ADD ${TOOLNAME}/focus2result.py.patch ${PREFIX}/src/${TOOLNAME}/
RUN patch ${PREFIX}/src/${TOOLNAME}/focus2result.py < ${PREFIX}/src/${TOOLNAME}/focus2result.py.patch
ADD ${TOOLNAME}/focus_cami.py.patch ${PREFIX}/src/${TOOLNAME}/
RUN patch ${PREFIX}/src/${TOOLNAME}/focus_cami.py < ${PREFIX}/src/${TOOLNAME}/focus_cami.py.patch

ADD inputlist_reads_interleaved.txt ${IO}/

ENV PATH=${PREFIX}/bin:${PATH}
ENV CONT_PAIRED_FASTQ_FILE_LISTING ${IO}/inputlist_reads_interleaved.txt
#~ #ENV CONT_CONTIGS_FILE_LISTING ${IO}/inputlist_contigs.txt
ENV CONT_PROFILING_FILES ${IO}/output/

ADD ${TOOLNAME}/task_${TOOLNAME}.pl ${PREFIX}/bin/task.pl
RUN chmod a+x ${PREFIX}/bin/task.pl


ENTRYPOINT ["task.pl"]
