FROM linsalrob/cfk8bd:latest
MAINTAINER Stefan Janssen, stefan.m.janssen@gmail.com
ENV TOOLNAME focus

#needed if on Michaels cluster
#~ ENV http_proxy http://172.16.20.249:3128
#~ ENV https_proxy http://172.16.20.249:3128

#update underlying linux system
RUN apt-get update -y

#list of all dependencies that can be satisfied via the package management system of Ubuntu
ENV PACKAGES wget curl unzip seqtk make
#install dependencies
RUN apt-get install -y --no-install-recommends ${PACKAGES}

#directory where additional software shall be installed
ENV PREFIX /biobox/
#create prefix directory and src subdirectory
RUN mkdir -p ${PREFIX}/src/ ${PREFIX}/bin/ ${PREFIX}/lib/ ${PREFIX}/share/ 
ENV PATH=${PREFIX}/bin:${PATH}



#update program to Stefans standards
RUN mkdir -p ${PREFIX}/src/${TOOLNAME}
RUN mv /home/* ${PREFIX}/src/${TOOLNAME}
ADD ${TOOLNAME}/focus2result.py.patch ${PREFIX}/src/${TOOLNAME}/
RUN patch ${PREFIX}/src/${TOOLNAME}/focus2result.py < ${PREFIX}/src/${TOOLNAME}/focus2result.py.patch
ADD ${TOOLNAME}/focus_cami.py.patch ${PREFIX}/src/${TOOLNAME}/
RUN patch ${PREFIX}/src/${TOOLNAME}/focus_cami.py < ${PREFIX}/src/${TOOLNAME}/focus_cami.py.patch


#add my Perl scripts
ADD Utils.pm ${PREFIX}/lib/
ADD YAML.pm ${PREFIX}/lib/
ADD ${TOOLNAME}/task_${TOOLNAME}.pl ${PREFIX}/bin/task.pl
RUN chmod a+x ${PREFIX}/bin/task.pl

ENV YAML "/bbx/input/biobox.yaml"
ENTRYPOINT ["task.pl"]
