FROM gobics/taxypro
MAINTAINER Stefan Janssen, stefan.m.janssen@gmail.com
ENV TOOLNAME taxypro

#needed if on Michaels cluster
#~ ENV http_proxy http://172.16.20.249:3128
#~ ENV https_proxy http://172.16.20.249:3128




#list of all dependencies that can be satisfied via the package management system of Ubuntu
ENV PACKAGES dpatch make
#install dependencies
RUN apt-get install -y --no-install-recommends ${PACKAGES}

#directory where additional software shall be installed
ENV PREFIX /biobox/
#create prefix directory and src subdirectory
RUN mkdir -p ${PREFIX}/src/ ${PREFIX}/bin/ ${PREFIX}/lib/ ${PREFIX}/share/ 
ENV PATH=${PREFIX}/bin:${PATH}



#create prefix directory and src subdirectory
ADD ${TOOLNAME}/octave.script ${PREFIX}/src/${TOOLNAME}/
RUN chmod a+x ${PREFIX}/src/${TOOLNAME}/octave.script
ADD ${TOOLNAME}/TaxyProMain.m.patch ${PREFIX}/src/${TOOLNAME}/
RUN patch /home/Tool/Taxy-Pro/TaxyProMain.m < ${PREFIX}/src/${TOOLNAME}/TaxyProMain.m.patch

#add my Perl scripts
ADD Utils.pm ${PREFIX}/lib/
ADD YAML.pm ${PREFIX}/lib/
ADD ${TOOLNAME}/task_${TOOLNAME}.pl ${PREFIX}/bin/task.pl
RUN chmod a+x ${PREFIX}/bin/task.pl

ENV YAML "/bbx/input/biobox.yaml"
ENTRYPOINT ["task.pl"]
