FROM ubuntu:14.04
MAINTAINER Stefan Janssen, stefan.m.janssen@gmail.com

#needed if on Michaels cluster
ENV http_proxy http://172.16.20.249:3128
ENV https_proxy http://172.16.20.249:3128

ENV TOOLNAME phylosift

#list of all dependencies that can be satisfied via the package management system of Ubuntu
ENV PACKAGES wget curl
#directory where additional software shall be installed
ENV PREFIX /biobox/
#directory for in and output with the host system
ENV IO /exchange/

#update underlying linux system
RUN apt-get update -y

#install dependencies
RUN apt-get install -y --no-install-recommends ${PACKAGES}

#create prefix directory and src subdirectory
RUN mkdir -p ${PREFIX}/src
#download the latest version of PhyloSift
RUN wget -q -O ${PREFIX}/src/phylosift.tar.bz2 http://edhar.genomecenter.ucdavis.edu/~koadman/phylosift/phylosift_latest.tar.bz2
#extract downloaded archive
RUN tar xjvf ${PREFIX}/src/phylosift.tar.bz2 -C ${PREFIX}/src/
#determine directory name and rename this directory into ${TOOLNAME}
RUN cn=`find ${PREFIX}/src/ -name "phylosift_*" -type d` && mv $cn ${PREFIX}/src/${TOOLNAME}
RUN echo '' >> ${PREFIX}/src/${TOOLNAME}/phylosiftrc;
#increase the maximum allowed memory consumption for Infernal tools from 2.5 GB to 10 GB
RUN echo '$cm_align_long_mxsize = "40000";' >> ${PREFIX}/src/${TOOLNAME}/phylosiftrc;
RUN echo '$cm_align_short_mxsize = "40000";' >> ${PREFIX}/src/${TOOLNAME}/phylosiftrc;
RUN rm ${PREFIX}/src/phylosift.tar.bz2

#replace phylosifts own copy of the NCBI taxonomy with the latest one from NCBI's FTP server
RUN mkdir -p ${HOME}/share/phylosift/ncbi/
RUN wget -q -O ${HOME}/share/phylosift/ncbi/taxdump.tar.gz ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
RUN tar xzvf ${HOME}/share/phylosift/ncbi/taxdump.tar.gz -C ${HOME}/share/phylosift/ncbi/
RUN rm ${HOME}/share/phylosift/ncbi/taxdump.tar.gz
#note the download date of the NCBI taxonomy
RUN date +"%Y.%m.%d" > ${HOME}/share/phylosift/ncbi/taxdump.tar.gz.date

#normally phylosift downloads its marker database when it is executed the first time. I want to have the download ready when building the container, thus it is done here manually
RUN wget -q -O ${HOME}/share/phylosift/markers.tgz http://edhar.genomecenter.ucdavis.edu/~koadman/phylosift_markers/markers.tgz
RUN tar xzvf ${HOME}/share/phylosift/markers.tgz -C ${HOME}/share/phylosift/
RUN rm ${HOME}/share/phylosift/markers.tgz

RUN mkdir -p ${PREFIX}/bin/

RUN mkdir -p ${IO}/input/
RUN mkdir -p ${IO}/output/
RUN mkdir -p /tmp/${TOOLNAME}_run/
#ADD inputlist_contigs.txt inputlist_reads_interleaved.txt ${IO}/
ADD inputlist_contigs.txt ${IO}/

ENV PATH=${PREFIX}/bin:${PATH}
#ENV CONT_PAIRED_FASTQ_FILE_LISTING ${IO}/inputlist_reads_interleaved.txt
ENV CONT_CONTIGS_FILE_LISTING ${IO}/inputlist_contigs.txt
ENV CONT_PROFILING_FILES ${IO}/output/

#phylosift is using the NCBI taxonomy, but the output format is not strictly that of the CAMI challenge, thus the original output must be converted
ENV MAPPERNAME IDmapper
ADD Utils.pm ${PREFIX}/src/${MAPPERNAME}/
ADD ${TOOLNAME}/convert_${TOOLNAME}.pl ${PREFIX}/src/${MAPPERNAME}/convert.pl
ADD ${TOOLNAME}/task_${TOOLNAME}.pl ${PREFIX}/bin/task.pl
RUN chmod a+x ${PREFIX}/bin/task.pl

ENTRYPOINT ["task.pl"]
