FROM ubuntu:14.04
MAINTAINER Stefan Janssen, stefan.m.janssen@gmail.com
ENV TOOLNAME motu

#needed if on Michaels cluster
ENV http_proxy http://172.16.20.249:3128
ENV https_proxy http://172.16.20.249:3128

#update underlying linux system
RUN apt-get update -y

#list of all dependencies that can be satisfied via the package management system of Ubuntu
ENV PACKAGES wget curl bc
#install dependencies
RUN apt-get install -y --no-install-recommends ${PACKAGES}


#directory where additional software shall be installed
ENV PREFIX /biobox/
#directory for in and output with the host system
ENV IO /exchange/


#create prefix directory and src subdirectory
RUN mkdir -p ${PREFIX}/src/${TOOLNAME}/
RUN mkdir -p ${PREFIX}/bin/
RUN mkdir -p ${PREFIX}/share/

RUN mkdir -p ${IO}/input/
RUN mkdir -p ${IO}/output/

#download the latest version of mOTU
RUN wget -q -O ${PREFIX}/src/${TOOLNAME}/motu.tar.gz http://www.bork.embl.de/software/mOTU/share/mOTUs.Linux64bits.tar.gz
#extract downloaded archive
RUN tar xzvf ${PREFIX}/src/${TOOLNAME}/motu.tar.gz -C ${PREFIX}/src/${TOOLNAME}/
RUN rm -f ${PREFIX}/src/${TOOLNAME}/motu.tar.gz

#download the NCBI taxonomy from NCBI's FTP server
RUN mkdir -p ${PREFIX}/share/taxonomy/
RUN wget -q -O ${PREFIX}/share/taxonomy/taxdump.tar.gz ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
RUN tar xzvf ${PREFIX}/share/taxonomy/taxdump.tar.gz -C ${PREFIX}/share/taxonomy/
RUN rm -f ${PREFIX}/share/taxonomy/taxdump.tar.gz
#note the download date of the NCBI taxonomy
RUN date +"%Y.%m.%d" > ${PREFIX}/share/taxonomy/taxdump.tar.gz.date

ENV MAPPERNAME IDmapper
ADD Utils.pm ${PREFIX}/src/${MAPPERNAME}/
ADD ${TOOLNAME}/convert_${TOOLNAME}.pl ${PREFIX}/src/${MAPPERNAME}/convert.pl

ADD inputlist_reads_interleaved.txt ${IO}/

ENV PATH=${PREFIX}/bin:${PATH}
ENV CONT_PAIRED_FASTQ_FILE_LISTING ${IO}/inputlist_reads_interleaved.txt
#ENV CONT_CONTIGS_FILE_LISTING ${IO}/inputlist_contigs.txt
ENV CONT_PROFILING_FILES ${IO}/output/

#phylosift is using the NCBI taxonomy, but the output format is not strictly that of the CAMI challenge, thus the original output must be converted
ADD ${TOOLNAME}/task_${TOOLNAME}.pl ${PREFIX}/bin/task.pl
RUN chmod a+x ${PREFIX}/bin/task.pl


ENTRYPOINT ["task.pl"]
