FROM ubuntu:14.04
MAINTAINER Stefan Janssen, stefan.m.janssen@gmail.com
ENV TOOLNAME motu

#needed if on Michaels cluster
#~ ENV http_proxy http://172.16.20.249:3128
#~ ENV https_proxy http://172.16.20.249:3128

#update underlying linux system
RUN apt-get update -y

#list of all dependencies that can be satisfied via the package management system of Ubuntu
ENV PACKAGES wget curl bc make
#install dependencies
RUN apt-get install -y --no-install-recommends ${PACKAGES}

#directory where additional software shall be installed
ENV PREFIX /biobox/
#create prefix directory and src subdirectory
RUN mkdir -p ${PREFIX}/src/ ${PREFIX}/bin/ ${PREFIX}/lib/ ${PREFIX}/share/ 
ENV PATH=${PREFIX}/bin:${PATH}



#download the latest version of mOTU
RUN wget -q -O ${PREFIX}/src/${TOOLNAME}.tar.gz http://www.bork.embl.de/software/mOTU/share/mOTUs.Linux64bits.tar.gz
#extract downloaded archive
RUN mkdir -p ${PREFIX}/src/${TOOLNAME}
RUN tar xzvf ${PREFIX}/src/${TOOLNAME}.tar.gz -C ${PREFIX}/src/${TOOLNAME}/
RUN rm -f ${PREFIX}/src/${TOOLNAME}.tar.gz



#download the NCBI taxonomy from NCBI's FTP server
ADD downloadTaxonomy.pl ${PREFIX}/bin/
RUN downloadTaxonomy.pl ${PREFIX}/share/taxonomy/

#add my Perl scripts
ADD Utils.pm ${PREFIX}/lib/
ADD YAML.pm ${PREFIX}/lib/
ADD ${TOOLNAME}/convert_${TOOLNAME}.pl ${PREFIX}/bin/convert.pl
ADD ${TOOLNAME}/task_${TOOLNAME}.pl ${PREFIX}/bin/task.pl
RUN chmod a+x ${PREFIX}/bin/task.pl ${PREFIX}/bin/downloadTaxonomy.pl ${PREFIX}/bin/convert.pl 

ENV YAML "/bbx/input/biobox.yaml"
ENTRYPOINT ["task.pl"]
