FROM ubuntu:14.04
MAINTAINER Stefan Janssen, stefan.m.janssen@gmail.com
ENV TOOLNAME amphora2

#needed if on Michaels cluster
ENV http_proxy http://172.16.20.249:3128
ENV https_proxy http://172.16.20.249:3128

#update underlying linux system
RUN apt-get update -y

#list of all dependencies that can be satisfied via the package management system of Ubuntu
ENV PACKAGES wget curl git ca-certificates make libc6-dev libc-dev gcc-4.8-locales gcc-multilib manpages-dev autoconf automake1.9 libtool flex bison gdb gcc-4.8-multilib libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan0-dbg libtsan0-dbg libquadmath0-dbg gcc cpanminus clustalo libgd-perl bioperl emboss patch
#install dependencies
RUN apt-get install -y --no-install-recommends ${PACKAGES}

ENV MAPPERNAME IDmapper

#directory where additional software shall be installed
ENV PREFIX /biobox/
#directory for in and output with the host system
ENV IO /exchange/
  

#create prefix directory and src subdirectory
RUN mkdir -p ${PREFIX}/src
RUN git clone https://github.com/martinwu/AMPHORA2.git ${PREFIX}/src/${TOOLNAME}

##install dependencies:
RUN mkdir -p ${PREFIX}/bin/
ENV PATH=${PREFIX}/bin:${PATH}
#hmmer3
RUN wget -q -O ${PREFIX}/src/hmmer3.tgz http://selab.janelia.org/software/hmmer3/3.0/hmmer-3.0.tar.gz
RUN tar xzvf ${PREFIX}/src/hmmer3.tgz -C ${PREFIX}/src/
RUN rm ${PREFIX}/src/hmmer3.tgz
RUN cn=`find ${PREFIX}/src/ -name "hmmer-*" -type d` && mv $cn ${PREFIX}/src/hmmer3
RUN cd ${PREFIX}/src/hmmer3 && ./configure --prefix=${PREFIX} && make && make install

#raxml
RUN git clone https://github.com/stamatak/standard-RAxML.git ${PREFIX}/src/raxml
RUN cd ${PREFIX}/src/raxml && make -f Makefile.gcc && rm *.o
RUN cd ${PREFIX}/src/raxml && make -f Makefile.PTHREADS.gcc && rm *.o
RUN cp ${PREFIX}/src/raxml/raxmlHPC* ${PREFIX}/bin/

#bioperl
RUN cpanm -v LWP::Simple

##patch bioperl to operate with strange Newick trees
ADD ${TOOLNAME}/bioperl_newick.patch ${PREFIX}/src/
RUN patch /usr/share/perl5/Bio/TreeIO/NewickParser.pm < ${PREFIX}/src/bioperl_newick.patch

#replace amphoras version of the NCBI taxonomy with a more current one
RUN wget -q -O ${PREFIX}/src/${TOOLNAME}/Taxonomy/taxdump.tar.gz ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
#note the download date of the NCBI taxonomy
RUN date +"%Y.%m.%d" > ${PREFIX}/src/${TOOLNAME}/Taxonomy/taxdump.tar.gz.date
RUN tar xzvf ${PREFIX}/src/${TOOLNAME}/Taxonomy/taxdump.tar.gz -C ${PREFIX}/src/${TOOLNAME}/Taxonomy/
RUN rm ${PREFIX}/src/${TOOLNAME}/Taxonomy/taxdump.tar.gz
ADD ${TOOLNAME}/contig.taxonid.patch ${PREFIX}/src/${TOOLNAME}/Taxonomy/
RUN patch ${PREFIX}/src/${TOOLNAME}/Taxonomy/contig.taxonid < ${PREFIX}/src/${TOOLNAME}/Taxonomy/contig.taxonid.patch
#check if all taxonIDs in contig.taxonid are still in the updated taxonomy
ADD Utils.pm ${PREFIX}/src/${MAPPERNAME}/
ADD ${TOOLNAME}/checkTaxids.pl ${PREFIX}/src/${MAPPERNAME}/checkTaxids.pl
RUN perl -I ${PREFIX}/src/${MAPPERNAME}/ ${PREFIX}/src/${MAPPERNAME}/checkTaxids.pl ${PREFIX}/src/${TOOLNAME}/Taxonomy/contig.taxonid ${PREFIX}/src/${TOOLNAME}/Taxonomy/
#fix phylosift such that it reports NCBI taxonomy IDs instead of scientific names
ADD ${TOOLNAME}/Phylotyping.pl.patch ${PREFIX}/src/${TOOLNAME}/Scripts/
RUN patch ${PREFIX}/src/${TOOLNAME}/Scripts/Phylotyping.pl < ${PREFIX}/src/${TOOLNAME}/Scripts/Phylotyping.pl.patch

ENV AMPHORA2_home ${PREFIX}/src/${TOOLNAME}

RUN mkdir -p ${IO}/input/
RUN mkdir -p ${IO}/output/
RUN mkdir -p /tmp/${TOOLNAME}_run/
ADD inputlist_contigs.txt ${IO}/

ENV CONT_CONTIGS_FILE_LISTING ${IO}/inputlist_contigs.txt
ENV CONT_PROFILING_FILES ${IO}/output/

ADD ${TOOLNAME}/convert_${TOOLNAME}.pl ${PREFIX}/src/${MAPPERNAME}/convert.pl
ADD ${TOOLNAME}/task_${TOOLNAME}.pl ${PREFIX}/bin/task.pl
RUN chmod a+x ${PREFIX}/bin/task.pl

#~ cd /tmp
#~ perl /biobox/src/amphora2/Scripts/MarkerScanner.pl -Bacteria -DNA /biobox/src/amphora2/TestData/ecoli.fasta
#~ perl /biobox/src/amphora2/Scripts/MarkerAlignTrim.pl -WithReference -OutputFormat phylip
#~ perl /biobox/src/amphora2/Scripts/Phylotyping.pl -CPUs 6 > phylotype.result


ENTRYPOINT ["task.pl"]
